# Generated by Django 2.2.6 on 2020-09-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200923_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
    ]
