# Generated by Django 2.2.6 on 2020-09-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_remove_publisher_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='p_library.Book'),
        ),
    ]
