# Generated by Django 2.2.6 on 2020-09-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
    ]
