# Generated by Django 2.2.6 on 2020-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_book_pubkisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubkisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='p_library.Publisher'),
        ),
    ]
